<template>
  <div>
    <button @click="upvote()" style="border:none; background-color:white;">
      <!-- Generated by IcoMoon.io -->
      <svg
        v-bind:style="{ 'fill': colorup }"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="2em"
        height="2em"
        viewBox="0 0 512 512"
        id="up"
      >
        <title />
        <g id="icomoon-ignore" />
        <path
          d="M438.627 201.373l-160-160c-12.496-12.497-32.757-12.497-45.254 0l-160 160c-12.497 12.497-12.497 32.758 0 45.255s32.758 12.498 45.255 0l105.372-105.373v306.745c0 17.673 14.327 32 32 32s32-14.327 32-32v-306.745l105.373 105.373c6.248 6.248 14.438 9.372 22.627 9.372s16.379-3.124 22.627-9.373c12.497-12.497 12.497-32.757 0-45.254z"
        />
      </svg>
    </button>
    <label id=" votelabel" for v-text="test2"></label>
    <button @click="downvote()" style="border:none; background-color:white;">
      <!-- Generated by IcoMoon.io -->
      <svg
        v-bind:style="{ 'fill': colordown }"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="2em"
        height="2em"
        viewBox="0 0 512 512"
        id="down"
      >
        <title />
        <g id="icomoon-ignore" />
        <path
          d="M438.627 310.627l-160 160c-12.496 12.497-32.757 12.497-45.254 0l-160-160c-12.497-12.497-12.497-32.758 0-45.255s32.758-12.498 45.255 0l105.372 105.373v-306.745c0-17.673 14.327-32 32-32s32 14.327 32 32v306.745l105.373-105.373c6.248-6.248 14.438-9.372 22.627-9.372s16.379 3.124 22.627 9.373c12.497 12.497 12.497 32.757 0 45.254z"
        />
      </svg>
    </button>
  </div>
</template>

<script>
export default {
  props: ["postId", "test", "uservotes"],

  mounted() {
    var vote = JSON.parse(this.uvotes);
    var id = this.post_id;

    for (var i = 0; i < Object.keys(vote).length; i++) {
      if (vote[i]["post_id"] == id) {
        if (vote[i]["vote_type"] == "UP") {
          this.colorup = "rgba(197, 55, 0)";
        } else if (vote[i]["vote_type"] == "DOWN") {
          this.colordown = "rgba(95, 115, 203)";
        }
      }
    }
  },
  data: function() {
    return {
      test2: this.test,
      colorup: "",
      colordown: "",
      uvotes: this.uservotes,
      post_id: this.postId
    };
  },
  methods: {
    upvote() {
      axios
        .post("/vote/" + this.postId)
        .then(response => {
          console.log(response.data);
          if (this.colordown == "rgba(95, 115, 203)") {
            this.colordown = "";
          }
          if (this.colorup == "rgba(197, 55, 0)") {
            this.colorup = "";
          } else {
            this.colorup = "rgba(197, 55, 0)";
          }

          this.test2 = response.data;
        })
        .catch(errors => {
          if (errors.response.status == 401) {
            window.location = "/login";
          }
        });
    },
    downvote() {
      axios
        .post("/voted/" + this.postId)
        .then(response => {
          if (this.colorup == "rgba(197, 55, 0)") {
            this.colorup = "";
          }
          if (this.colordown == "rgba(95, 115, 203)") {
            this.colordown = "";
          } else {
            this.colordown = "rgba(95, 115, 203)";
          }

          this.test2 = response.data;
        })
        .catch(errors => {
          if (errors.response.status == 401) {
            window.location = "/login";
          }
        });
    }
  }
};
</script>
